name: Mostrar mensaje
on:
 push:
  branch: [ main ]
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
  - name: Mostrar el mensaje por la pantalla
    run:
      echo "hola desde el runner de github action"
  - name: Mostrar fecha y hora
    run:
      echo "Fecha y hora de ejecución:"
      date
  - name: Mostrar version de java
    run: |
      java -v
      echo "Version de java comprobadad con éxito"
      
      